{% set version = "3.3.8" %}

package:
  name: django-import-export
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/django-import-export/django-import-export-{{ version }}.tar.gz
  sha256: 4deabc557801d368093608c86fd0f4831bc9540e2ea41ca2f023e2efb3eb6f48

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - diff-match-patch
    - django >=3.2
    - tablib ==3.5.0

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - import_export
    - import_export.formats
    - import_export.templatetags

about:
  home: https://github.com/bmihelac/django-import-export
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Django application and library for importing and exporting data with included admin integration

extra:
  recipe-maintainers:
    - ocefpaf
