{% set version = "4.1.1" %}

package:
  name: django-import-export
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/django-import-export/django_import_export-{{ version }}.tar.gz
  sha256: 16ecc5a9f0df46bde6eb278a3e65ebda0ee1db55656f36440e9fb83f40ab85a3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - diff-match-patch
    - django >=3.2
    - tablib ==3.5.0

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - import_export
    - import_export.formats
    - import_export.templatetags

about:
  home: https://github.com/bmihelac/django-import-export
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Django application and library for importing and exporting data with included admin integration

extra:
  recipe-maintainers:
    - ocefpaf
